### ISSUE TITLE
请问是版本问题吗

### ISSUE THREAD

**Issue by caoxudong0513** [Z1zyw/VQ-Map#1]
![image](https://github.com/user-attachments/assets/536eec93-0374-40ec-b312-2a7a685ac08d)
Package                       Version        Editable project location
----------------------------- -------------- -----------------------------------------
absl-py                       2.1.0
actionlib                     1.14.0
addict                        2.4.0
angles                        1.9.13
bondpy                        1.8.6
cachetools                    5.5.0
camera-calibration            1.17.0
camera-calibration-parsers    1.12.0
catkin                        0.8.10
certifi                       2024.8.30
charset-normalizer            3.4.0
contourpy                     1.1.1
controller-manager            0.20.0
controller-manager-msgs       0.20.0
cv-bridge                     1.16.2
cycler                        0.12.1
descartes                     1.1.0
diagnostic-analysis           1.11.0
diagnostic-common-diagnostics 1.11.0
diagnostic-updater            1.11.0
dynamic-reconfigure           1.7.3
fire                          0.7.0
fonttools                     4.55.3
gazebo_plugins                2.9.2
gazebo_ros                    2.9.2
gencpp                        0.7.0
geneus                        3.0.0
genlisp                       0.4.18
genmsg                        0.6.0
gennodejs                     2.0.2
genpy                         0.6.15
google-auth                   2.37.0
google-auth-oauthlib          1.0.0
grpcio                        1.68.1
h5py                          3.11.0
idna                          3.10
image-geometry                1.16.2
importlib_metadata            8.5.0
importlib_resources           6.4.5
interactive-markers           1.12.0
joblib                        1.4.2
joint-state-publisher         1.15.1
joint-state-publisher-gui     1.15.1
kiwisolver                    1.4.7
laser_geometry                1.6.7
llvmlite                      0.31.0
loguru                        0.7.3
Markdown                      3.7
MarkupSafe                    2.1.5
matplotlib                    3.5.3
message-filters               1.16.0
mkl-fft                       1.3.8
mkl-random                    1.2.4
mkl-service                   2.4.0
mmcv                          1.4.0
mmcv-full                     1.4.0
mmdet                         2.20.0
mmdet3d                       0.0.0          /home/ubuntu/code/model/VQ-Map/vq_map_sur
mpi4py                        3.0.3
msgpack                       1.1.0
msgpack-numpy                 0.4.8
multimethod                   1.10
MultiScaleDeformableAttention 1.0
numba                         0.48.0
numpy                         1.23.0
nuscenes-devkit               1.1.11
oauthlib                      3.2.2
opencv-python                 4.10.0.84
packaging                     24.2
Pillow                        8.4.0
pip                           24.2
platformdirs                  4.3.6
protobuf                      5.29.1
psutil                        6.1.0
pyasn1                        0.6.1
pyasn1_modules                0.4.1
pycocotools                   2.0.7
pyparsing                     3.1.4
pyquaternion                  0.9.9
python-dateutil               2.9.0.post0
python-qt-binding             0.4.4
PyYAML                        6.0.2
pyzmq                         26.2.0
qt-dotgraph                   0.4.2
qt-gui                        0.4.2
qt-gui-cpp                    0.4.2
qt-gui-py-common              0.4.2
requests                      2.32.3
requests-oauthlib             2.0.0
resource_retriever            1.12.7
rosbag                        1.16.0
rosboost-cfg                  1.15.8
rosclean                      1.15.8
roscreate                     1.15.8
rosgraph                      1.16.0
roslaunch                     1.16.0
roslib                        1.15.8
roslint                       0.12.0
roslz4                        1.16.0
rosmake                       1.15.8
rosmaster                     1.16.0
rosmsg                        1.16.0
rosnode                       1.16.0
rosparam                      1.16.0
rospy                         1.16.0
rosservice                    1.16.0
rostest                       1.16.0
rostopic                      1.16.0
rosunit                       1.15.8
roswtf                        1.16.0
rqt_action                    0.4.9
rqt_bag                       0.5.1
rqt_bag_plugins               0.5.1
rqt-console                   0.4.12
rqt_dep                       0.4.12
rqt_graph                     0.4.14
rqt_gui                       0.5.3
rqt_gui_py                    0.5.3
rqt-image-view                0.4.17
rqt_launch                    0.4.9
rqt-logger-level              0.4.12
rqt-moveit                    0.5.11
rqt_msg                       0.4.10
rqt_nav_view                  0.5.7
rqt_plot                      0.4.13
rqt_pose_view                 0.5.11
rqt_publisher                 0.4.10
rqt_py_common                 0.5.3
rqt_py_console                0.4.10
rqt-reconfigure               0.5.5
rqt-robot-dashboard           0.5.8
rqt-robot-monitor             0.5.15
rqt_robot_steering            0.5.12
rqt-runtime-monitor           0.5.10
rqt-rviz                      0.7.0
rqt_service_caller            0.4.10
rqt_shell                     0.4.11
rqt_srv                       0.4.9
rqt-tf-tree                   0.6.4
rqt_top                       0.4.10
rqt_topic                     0.4.13
rqt_web                       0.4.10
rsa                           4.9
rviz                          1.14.20
scikit-learn                  1.3.2
scipy                         1.10.1
sensor-msgs                   1.13.1
setuptools                    58.0.4
Shapely                       1.8.5.post1
six                           1.17.0
smach                         2.5.2
smach-ros                     2.5.2
smclib                        1.8.6
tabulate                      0.9.0
tensorboard                   2.14.0
tensorboard-data-server       0.7.2
tensorpack                    0.11
termcolor                     2.4.0
terminaltables                3.1.10
tf                            1.13.2
tf-conversions                1.13.2
tf2-geometry-msgs             0.7.7
tf2-kdl                       0.7.7
tf2-py                        0.7.7
tf2-ros                       0.7.7
threadpoolctl                 3.5.0
toml                          0.10.2
tomli                         2.2.1
topic-tools                   1.16.0
torch                         1.10.0+cu113
torchaudio                    0.10.0+rocm4.1
torchpack                     0.3.1
torchvision                   0.11.0+cu113
tqdm                          4.67.1
typing_extensions             4.11.0
urllib3                       2.2.3
Werkzeug                      3.0.6
wheel                         0.44.0
xacro                         1.14.16
yapf                          0.43.0
zipp                          3.20.2

**Comment by Z1zyw** [comment]
这应该不是版本问题，但你可以试着忽视它。只要 check_forward_equal_with_pytorch_float() 没有问题，后续代码应该能够正常运行。

**Comment by Z1zyw** [comment]
这不是版本问题，这是因为 vq_map_sur/other/ops/functions/ms_deform_attn_func.py 中 line25-26 value 被强制转换成float32，但你也可以试着忽视它。只要 check_forward_equal_with_pytorch_float() 没有问题，后续代码应该能够正常运行。
